### PR TITLE
Replace deprecated and use power of WORKDIR instruction

### PR DESCRIPTION
**Pull request by MaxymVlasov**
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
https://docs.docker.com/engine/reference/builder/#workdir

### CODE REVIEW

**Comment by MaxymVlasov** [comment]
Also, for what purpose you use the `latest` tag, not combine `RUN` installation instructions and remove apt-get cache and curl?

**Review by brikis98 — APPROVED** [review]
Nice improvements, thanks!

**Comment by brikis98** [comment]
> Also, for what purpose you use the `latest` tag

Where?

> not combine `RUN` installation instructions and not remove apt-get cache and curl?

This is example code, meant for a tutorial, so we keep it as simple as we can. If this was production code, then yes, we'd want to optimize it more as you said.

**Comment by MaxymVlasov** [comment]
@brikis98 in [this Dockerfile](https://github.com/gruntwork-io/infrastructure-as-code-training/blob/c8518cd7143c55b020319163c6929a0a8524e476/docker-example/Dockerfile#L1) used `FROM ubuntu:latest` instruction.

I agree that big docker images can make some troubles, but it's not destructive, so simplification here is totally okay. But are you sure that we need not pin the image version in the example for simplification?
At least, without saying 'do not do this in real-world'

**Comment by brikis98** [comment]
Pinning versions is always a trade-off for this sort of example code. The advantage is that the code is likely to keep working consistently in the long term, which is good; the drawback is that you then need to put in manual effort to update to the latest versions, and things could break when old versions are discontinued. That said, a comment explaining this is prob worth adding!

**Pull request merged**
